apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
  - image: ghcr.io/shipperizer/druid
    custom:
      buildCommand: DOCKERFILE=distribution/docker/Dockerfile ./buildx.sh
      dependencies:
        dockerfile:
          path: distribution/docker/Dockerfile
  # - image: ghcr.io/shipperizer/druid
  #   docker:
  #     dockerfile: distribution/docker/Dockerfile.arm64
  local:
    push: true
